fix: Install `pexpect` to fix failing `regen_headers.sh`
While following the linux build directions in `BUILD.md`, the script `scripts/regen_headers.sh` fails to generate DroneCAN headers due to a missing python module:
```
Generating DroneCAN headers for libcanard
Traceback (most recent call last):
  File "/flash/arduremoteid/modules/dronecan_dsdlc/dronecan_dsdlc.py", line 20, in <module>
    from dronecan_dsdlc_tester import *
  File "/flash/arduremoteid/modules/dronecan_dsdlc/dronecan_dsdlc_tester.py", line 12, in <module>
    import pexpect
ModuleNotFoundError: No module named 'pexpect'
./scripts/regen_headers.sh: line 16: cd: libraries/DroneCAN_generated: No such file or directory
./scripts/regen_headers.sh: line 16: cd: libraries/DroneCAN_generated: No such file or directory
./scripts/regen_headers.sh: line 16: cd: libraries/DroneCAN_generated: No such file or directory
./scripts/regen_headers.sh: line 16: cd: libraries/DroneCAN_generated: No such file or directory
./scripts/regen_headers.sh: line 16: cd: libraries/DroneCAN_generated: No such file or directory
./scripts/regen_headers.sh: line 16: cd: libraries/DroneCAN_generated: No such file or directory
./scripts/regen_headers.sh: line 16: cd: libraries/DroneCAN_generated: No such file or directory
./scripts/regen_headers.sh: line 16: cd: libraries/DroneCAN_generated: No such file or directory
./scripts/regen_headers.sh: line 16: cd: libraries/DroneCAN_generated: No such file or directory
```

This issue is resolved (and build completed successfully) following a `pip install pexpect`.